name: Deploy to Google App Engine

on:
  push:
    branches:
      - master  # デプロイをトリガーするブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Generate GCP key file
      run: |
        echo "${{ secrets.GCP_SA_KEY_JSON }}" > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
      env:
        GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
        
    - name: Deploy to App Engine
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --quiet
